/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Ismael Lima
 */
public class ClientInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form ClientInterfaz
     */
    public ClientInterfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnRoomA1 = new javax.swing.JPanel();
        pnRoomB1 = new javax.swing.JPanel();
        pnRoomC1 = new javax.swing.JPanel();
        pnRoomD1 = new javax.swing.JPanel();
        pnRoomE1 = new javax.swing.JPanel();
        pnRoomA2 = new javax.swing.JPanel();
        pnRoomB2 = new javax.swing.JPanel();
        pnRoomC2 = new javax.swing.JPanel();
        pnRoomD2 = new javax.swing.JPanel();
        pnRoomE2 = new javax.swing.JPanel();
        pnRoomB3 = new javax.swing.JPanel();
        pnRoomA3 = new javax.swing.JPanel();
        pnRoomC3 = new javax.swing.JPanel();
        pnRoomD3 = new javax.swing.JPanel();
        pnRoomE3 = new javax.swing.JPanel();
        pnRoomD4 = new javax.swing.JPanel();
        pnRoomB4 = new javax.swing.JPanel();
        pnRoomA4 = new javax.swing.JPanel();
        pnRoomE4 = new javax.swing.JPanel();
        pnRoomC4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        cbRoomA1 = new javax.swing.JCheckBox();
        cbRoomA2 = new javax.swing.JCheckBox();
        cbRoomA3 = new javax.swing.JCheckBox();
        cbRoomA4 = new javax.swing.JCheckBox();
        cbRoomB1 = new javax.swing.JCheckBox();
        cbRoomB2 = new javax.swing.JCheckBox();
        cbRoomB3 = new javax.swing.JCheckBox();
        cbRoomB4 = new javax.swing.JCheckBox();
        cbRoomC1 = new javax.swing.JCheckBox();
        cbRoomC3 = new javax.swing.JCheckBox();
        cbRoomC2 = new javax.swing.JCheckBox();
        cbRoomC4 = new javax.swing.JCheckBox();
        cbRoomD3 = new javax.swing.JCheckBox();
        cbRoomD4 = new javax.swing.JCheckBox();
        cbRoomD1 = new javax.swing.JCheckBox();
        cbRoomD2 = new javax.swing.JCheckBox();
        cbRoomE2 = new javax.swing.JCheckBox();
        cbRoomE3 = new javax.swing.JCheckBox();
        cbRoomE4 = new javax.swing.JCheckBox();
        cbRoomE1 = new javax.swing.JCheckBox();
        lbErrorRoomsID = new javax.swing.JLabel();
        lbRoomsID = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfCheckInDate_Day = new javax.swing.JTextField();
        lbErrorCheckInDate = new javax.swing.JLabel();
        tfCheckInDate_Month = new javax.swing.JTextField();
        tfCheckInDate_Year = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbErrorCheckOutDate = new javax.swing.JLabel();
        tfCheckOutDate_Day = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfCheckOutDate_Month = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfCheckOutDate_Year = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReservations = new javax.swing.JTable();
        jPanel25 = new javax.swing.JPanel();
        btnCloseSesion = new javax.swing.JButton();
        btnReserve = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 250, 236));

        jPanel2.setBackground(new java.awt.Color(61, 61, 61));

        jPanel3.setBackground(new java.awt.Color(245, 236, 213));

        pnRoomA1.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomA1.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomA1Layout = new javax.swing.GroupLayout(pnRoomA1);
        pnRoomA1.setLayout(pnRoomA1Layout);
        pnRoomA1Layout.setHorizontalGroup(
            pnRoomA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomA1Layout.setVerticalGroup(
            pnRoomA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomB1.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomB1.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomB1Layout = new javax.swing.GroupLayout(pnRoomB1);
        pnRoomB1.setLayout(pnRoomB1Layout);
        pnRoomB1Layout.setHorizontalGroup(
            pnRoomB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomB1Layout.setVerticalGroup(
            pnRoomB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomC1.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomC1.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomC1Layout = new javax.swing.GroupLayout(pnRoomC1);
        pnRoomC1.setLayout(pnRoomC1Layout);
        pnRoomC1Layout.setHorizontalGroup(
            pnRoomC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomC1Layout.setVerticalGroup(
            pnRoomC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomD1.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomD1.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomD1Layout = new javax.swing.GroupLayout(pnRoomD1);
        pnRoomD1.setLayout(pnRoomD1Layout);
        pnRoomD1Layout.setHorizontalGroup(
            pnRoomD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomD1Layout.setVerticalGroup(
            pnRoomD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomE1.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomE1.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomE1Layout = new javax.swing.GroupLayout(pnRoomE1);
        pnRoomE1.setLayout(pnRoomE1Layout);
        pnRoomE1Layout.setHorizontalGroup(
            pnRoomE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomE1Layout.setVerticalGroup(
            pnRoomE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomA2.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomA2.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomA2Layout = new javax.swing.GroupLayout(pnRoomA2);
        pnRoomA2.setLayout(pnRoomA2Layout);
        pnRoomA2Layout.setHorizontalGroup(
            pnRoomA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomA2Layout.setVerticalGroup(
            pnRoomA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomB2.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomB2.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomB2Layout = new javax.swing.GroupLayout(pnRoomB2);
        pnRoomB2.setLayout(pnRoomB2Layout);
        pnRoomB2Layout.setHorizontalGroup(
            pnRoomB2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomB2Layout.setVerticalGroup(
            pnRoomB2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomC2.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomC2.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomC2Layout = new javax.swing.GroupLayout(pnRoomC2);
        pnRoomC2.setLayout(pnRoomC2Layout);
        pnRoomC2Layout.setHorizontalGroup(
            pnRoomC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomC2Layout.setVerticalGroup(
            pnRoomC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomD2.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomD2.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomD2Layout = new javax.swing.GroupLayout(pnRoomD2);
        pnRoomD2.setLayout(pnRoomD2Layout);
        pnRoomD2Layout.setHorizontalGroup(
            pnRoomD2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomD2Layout.setVerticalGroup(
            pnRoomD2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomE2.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomE2.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomE2Layout = new javax.swing.GroupLayout(pnRoomE2);
        pnRoomE2.setLayout(pnRoomE2Layout);
        pnRoomE2Layout.setHorizontalGroup(
            pnRoomE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomE2Layout.setVerticalGroup(
            pnRoomE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomB3.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomB3.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomB3Layout = new javax.swing.GroupLayout(pnRoomB3);
        pnRoomB3.setLayout(pnRoomB3Layout);
        pnRoomB3Layout.setHorizontalGroup(
            pnRoomB3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomB3Layout.setVerticalGroup(
            pnRoomB3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomA3.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomA3.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomA3Layout = new javax.swing.GroupLayout(pnRoomA3);
        pnRoomA3.setLayout(pnRoomA3Layout);
        pnRoomA3Layout.setHorizontalGroup(
            pnRoomA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomA3Layout.setVerticalGroup(
            pnRoomA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomC3.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomC3.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomC3Layout = new javax.swing.GroupLayout(pnRoomC3);
        pnRoomC3.setLayout(pnRoomC3Layout);
        pnRoomC3Layout.setHorizontalGroup(
            pnRoomC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomC3Layout.setVerticalGroup(
            pnRoomC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomD3.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomD3.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomD3Layout = new javax.swing.GroupLayout(pnRoomD3);
        pnRoomD3.setLayout(pnRoomD3Layout);
        pnRoomD3Layout.setHorizontalGroup(
            pnRoomD3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomD3Layout.setVerticalGroup(
            pnRoomD3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomE3.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomE3.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomE3Layout = new javax.swing.GroupLayout(pnRoomE3);
        pnRoomE3.setLayout(pnRoomE3Layout);
        pnRoomE3Layout.setHorizontalGroup(
            pnRoomE3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomE3Layout.setVerticalGroup(
            pnRoomE3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomD4.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomD4.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomD4Layout = new javax.swing.GroupLayout(pnRoomD4);
        pnRoomD4.setLayout(pnRoomD4Layout);
        pnRoomD4Layout.setHorizontalGroup(
            pnRoomD4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomD4Layout.setVerticalGroup(
            pnRoomD4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomB4.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomB4.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomB4Layout = new javax.swing.GroupLayout(pnRoomB4);
        pnRoomB4.setLayout(pnRoomB4Layout);
        pnRoomB4Layout.setHorizontalGroup(
            pnRoomB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomB4Layout.setVerticalGroup(
            pnRoomB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomA4.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomA4.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomA4Layout = new javax.swing.GroupLayout(pnRoomA4);
        pnRoomA4.setLayout(pnRoomA4Layout);
        pnRoomA4Layout.setHorizontalGroup(
            pnRoomA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomA4Layout.setVerticalGroup(
            pnRoomA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomE4.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomE4.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomE4Layout = new javax.swing.GroupLayout(pnRoomE4);
        pnRoomE4.setLayout(pnRoomE4Layout);
        pnRoomE4Layout.setHorizontalGroup(
            pnRoomE4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomE4Layout.setVerticalGroup(
            pnRoomE4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        pnRoomC4.setBackground(new java.awt.Color(255, 204, 51));
        pnRoomC4.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnRoomC4Layout = new javax.swing.GroupLayout(pnRoomC4);
        pnRoomC4.setLayout(pnRoomC4Layout);
        pnRoomC4Layout.setHorizontalGroup(
            pnRoomC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnRoomC4Layout.setVerticalGroup(
            pnRoomC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ismael Lima\\Documents\\GitHub\\SEGUNDO SEMESTRE - POO\\SEGUNDO_SEMESTRE-POO\\SEGUNDO_PARCIAL\\P2Lab2LimaAngel\\src\\main\\java\\View\\gate_3450186.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnRoomA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnRoomA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnRoomA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnRoomA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRoomE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRoomA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRoomA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRoomA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRoomA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoomE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setBackground(new java.awt.Color(245, 236, 213));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 61, 61));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOTEL");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 61, 61), 7, true));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel24.setBackground(new java.awt.Color(255, 250, 236));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Escoja su habitación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dubai", 1, 24), new java.awt.Color(61, 61, 61))); // NOI18N

        cbRoomA1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomA1.setText("A1");

        cbRoomA2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomA2.setText("A2");
        cbRoomA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomA2ActionPerformed(evt);
            }
        });

        cbRoomA3.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomA3.setText("A3");

        cbRoomA4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomA4.setText("A4");

        cbRoomB1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomB1.setText("B1");

        cbRoomB2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomB2.setText("B2");
        cbRoomB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomB2ActionPerformed(evt);
            }
        });

        cbRoomB3.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomB3.setText("B3");

        cbRoomB4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomB4.setText("B4");

        cbRoomC1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomC1.setText("C1");

        cbRoomC3.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomC3.setText("C3");

        cbRoomC2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomC2.setText("C2");
        cbRoomC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomC2ActionPerformed(evt);
            }
        });

        cbRoomC4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomC4.setText("C4");

        cbRoomD3.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomD3.setText("D3");

        cbRoomD4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomD4.setText("D4");

        cbRoomD1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomD1.setText("D1");

        cbRoomD2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomD2.setText("D2");
        cbRoomD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomD2ActionPerformed(evt);
            }
        });

        cbRoomE2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomE2.setText("E2");
        cbRoomE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomE2ActionPerformed(evt);
            }
        });

        cbRoomE3.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomE3.setText("E3");

        cbRoomE4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomE4.setText("E4");

        cbRoomE1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbRoomE1.setText("E1");
        cbRoomE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomE1ActionPerformed(evt);
            }
        });

        lbErrorRoomsID.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lbErrorRoomsID.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lbErrorRoomsID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbErrorRoomsID.setText("Error, debe escoger por lo menos un departamento.");

        lbRoomsID.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        lbRoomsID.setForeground(new java.awt.Color(204, 204, 204));
        lbRoomsID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoomsID.setText("Habitaciones adquiridas");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbErrorRoomsID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRoomA1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomA2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomA3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomA4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRoomB1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomB2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomB3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomB4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRoomC1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomC2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomC3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomC4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRoomD1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomD2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomD3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomD4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRoomE1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomE2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomE3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRoomE4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbRoomsID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(cbRoomA1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomA2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomA3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomA4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(cbRoomB1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomB2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomB3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomB4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(cbRoomC1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomC2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomC3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomC4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(cbRoomD1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomD2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomD3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomD4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(cbRoomE1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomE2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomE3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomE4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lbRoomsID)
                .addGap(3, 3, 3)
                .addComponent(lbErrorRoomsID)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel26.setBackground(new java.awt.Color(255, 250, 236));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ingrese las fechas de su reservación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dubai", 1, 24), new java.awt.Color(61, 61, 61))); // NOI18N
        jPanel26.setForeground(new java.awt.Color(61, 61, 61));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 61, 61));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha de entrada");

        tfCheckInDate_Day.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckInDate_Day.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckInDate_Day.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckInDate_Day.setText("00");
        tfCheckInDate_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckInDate_DayActionPerformed(evt);
            }
        });

        lbErrorCheckInDate.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lbErrorCheckInDate.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lbErrorCheckInDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbErrorCheckInDate.setText("Error, escriba una fecha válida.");

        tfCheckInDate_Month.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckInDate_Month.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckInDate_Month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckInDate_Month.setText("00");
        tfCheckInDate_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckInDate_MonthActionPerformed(evt);
            }
        });

        tfCheckInDate_Year.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckInDate_Year.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckInDate_Year.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckInDate_Year.setText("0000");
        tfCheckInDate_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckInDate_YearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(61, 61, 61));
        jLabel6.setText("/");

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(61, 61, 61));
        jLabel7.setText("/");

        jLabel14.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(61, 61, 61));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Fecha de salida");

        lbErrorCheckOutDate.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lbErrorCheckOutDate.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lbErrorCheckOutDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbErrorCheckOutDate.setText("Error, escriba una fecha válida.");

        tfCheckOutDate_Day.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckOutDate_Day.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckOutDate_Day.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckOutDate_Day.setText("00");
        tfCheckOutDate_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckOutDate_DayActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(61, 61, 61));
        jLabel16.setText("/");

        tfCheckOutDate_Month.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckOutDate_Month.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckOutDate_Month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckOutDate_Month.setText("00");
        tfCheckOutDate_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckOutDate_MonthActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(61, 61, 61));
        jLabel17.setText("/");

        tfCheckOutDate_Year.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckOutDate_Year.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckOutDate_Year.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckOutDate_Year.setText("0000");
        tfCheckOutDate_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckOutDate_YearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbErrorCheckInDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tfCheckInDate_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(tfCheckInDate_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(tfCheckInDate_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbErrorCheckOutDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tfCheckOutDate_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16)
                        .addGap(3, 3, 3)
                        .addComponent(tfCheckOutDate_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17)
                        .addGap(3, 3, 3)
                        .addComponent(tfCheckOutDate_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCheckInDate_Day)
                    .addComponent(jLabel6)
                    .addComponent(tfCheckInDate_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfCheckInDate_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfCheckOutDate_Day)
                    .addComponent(jLabel16)
                    .addComponent(tfCheckOutDate_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tfCheckOutDate_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbErrorCheckInDate)
                    .addComponent(lbErrorCheckOutDate))
                .addGap(12, 12, 12))
        );

        jPanel27.setBackground(new java.awt.Color(255, 250, 236));
        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Histórico de reservaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dubai", 1, 24), new java.awt.Color(61, 61, 61))); // NOI18N
        jPanel27.setForeground(new java.awt.Color(61, 61, 61));

        tbReservations.setBackground(new java.awt.Color(245, 236, 213));
        tbReservations.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tbReservations.setForeground(new java.awt.Color(61, 61, 61));
        tbReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Habitaciones", "Fecha de entrada", "Fecha de salida"
            }
        ));
        jScrollPane1.setViewportView(tbReservations);
        if (tbReservations.getColumnModel().getColumnCount() > 0) {
            tbReservations.getColumnModel().getColumn(0).setPreferredWidth(250);
            tbReservations.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbReservations.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel25.setBackground(new java.awt.Color(245, 236, 213));

        btnCloseSesion.setBackground(new java.awt.Color(61, 61, 61));
        btnCloseSesion.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnCloseSesion.setForeground(new java.awt.Color(255, 250, 236));
        btnCloseSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ismael Lima\\Documents\\GitHub\\SEGUNDO SEMESTRE - POO\\SEGUNDO_SEMESTRE-POO\\SEGUNDO_PARCIAL\\P2Lab2LimaAngel\\src\\main\\java\\View\\enter_13641113.png")); // NOI18N
        btnCloseSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseSesionActionPerformed(evt);
            }
        });

        btnReserve.setBackground(new java.awt.Color(87, 142, 126));
        btnReserve.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnReserve.setForeground(new java.awt.Color(255, 250, 236));
        btnReserve.setText("Reservar");

        btnClean.setBackground(new java.awt.Color(87, 142, 126));
        btnClean.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnClean.setForeground(new java.awt.Color(255, 250, 236));
        btnClean.setText("Limpiar");

        btnModify.setBackground(new java.awt.Color(87, 142, 126));
        btnModify.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnModify.setForeground(new java.awt.Color(255, 250, 236));
        btnModify.setText("Modificar");

        btnSearch.setBackground(new java.awt.Color(87, 142, 126));
        btnSearch.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 250, 236));
        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(87, 142, 126));
        btnDelete.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 250, 236));
        btnDelete.setText("Eliminar");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnCloseSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloseSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserve)
                    .addComponent(btnClean)
                    .addComponent(btnModify)
                    .addComponent(btnSearch)
                    .addComponent(btnDelete))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)))
                                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRoomA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoomA2ActionPerformed

    private void cbRoomB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoomB2ActionPerformed

    private void cbRoomC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoomC2ActionPerformed

    private void cbRoomD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoomD2ActionPerformed

    private void cbRoomE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoomE2ActionPerformed

    private void cbRoomE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoomE1ActionPerformed

    private void tfCheckInDate_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckInDate_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckInDate_YearActionPerformed

    private void tfCheckInDate_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckInDate_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckInDate_MonthActionPerformed

    private void tfCheckOutDate_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckOutDate_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckOutDate_DayActionPerformed

    private void tfCheckOutDate_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckOutDate_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckOutDate_MonthActionPerformed

    private void tfCheckOutDate_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckOutDate_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckOutDate_YearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tfCheckInDate_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckInDate_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckInDate_DayActionPerformed

    private void btnCloseSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClean;
    public javax.swing.JButton btnCloseSesion;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnModify;
    public javax.swing.JButton btnReserve;
    public javax.swing.JButton btnSearch;
    public javax.swing.JCheckBox cbRoomA1;
    public javax.swing.JCheckBox cbRoomA2;
    public javax.swing.JCheckBox cbRoomA3;
    public javax.swing.JCheckBox cbRoomA4;
    public javax.swing.JCheckBox cbRoomB1;
    public javax.swing.JCheckBox cbRoomB2;
    public javax.swing.JCheckBox cbRoomB3;
    public javax.swing.JCheckBox cbRoomB4;
    public javax.swing.JCheckBox cbRoomC1;
    public javax.swing.JCheckBox cbRoomC2;
    public javax.swing.JCheckBox cbRoomC3;
    public javax.swing.JCheckBox cbRoomC4;
    public javax.swing.JCheckBox cbRoomD1;
    public javax.swing.JCheckBox cbRoomD2;
    public javax.swing.JCheckBox cbRoomD3;
    public javax.swing.JCheckBox cbRoomD4;
    public javax.swing.JCheckBox cbRoomE1;
    public javax.swing.JCheckBox cbRoomE2;
    public javax.swing.JCheckBox cbRoomE3;
    public javax.swing.JCheckBox cbRoomE4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbErrorCheckInDate;
    public javax.swing.JLabel lbErrorCheckOutDate;
    public javax.swing.JLabel lbErrorRoomsID;
    public javax.swing.JLabel lbRoomsID;
    public javax.swing.JPanel pnRoomA1;
    public javax.swing.JPanel pnRoomA2;
    public javax.swing.JPanel pnRoomA3;
    public javax.swing.JPanel pnRoomA4;
    public javax.swing.JPanel pnRoomB1;
    public javax.swing.JPanel pnRoomB2;
    public javax.swing.JPanel pnRoomB3;
    public javax.swing.JPanel pnRoomB4;
    public javax.swing.JPanel pnRoomC1;
    public javax.swing.JPanel pnRoomC2;
    public javax.swing.JPanel pnRoomC3;
    public javax.swing.JPanel pnRoomC4;
    public javax.swing.JPanel pnRoomD1;
    public javax.swing.JPanel pnRoomD2;
    public javax.swing.JPanel pnRoomD3;
    public javax.swing.JPanel pnRoomD4;
    public javax.swing.JPanel pnRoomE1;
    public javax.swing.JPanel pnRoomE2;
    public javax.swing.JPanel pnRoomE3;
    public javax.swing.JPanel pnRoomE4;
    public javax.swing.JTable tbReservations;
    public javax.swing.JTextField tfCheckInDate_Day;
    public javax.swing.JTextField tfCheckInDate_Month;
    public javax.swing.JTextField tfCheckInDate_Year;
    public javax.swing.JTextField tfCheckOutDate_Day;
    public javax.swing.JTextField tfCheckOutDate_Month;
    public javax.swing.JTextField tfCheckOutDate_Year;
    // End of variables declaration//GEN-END:variables
}
