/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author USUARIO
 */
public class OptionsRoomsInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form ClientInterfaz2
     */
    public OptionsRoomsInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbGuests = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfCheckInDate_Day = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCheckInDate_Month = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfCheckInDate_Year = new javax.swing.JTextField();
        lbErrorCheckInDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCheckOutDate_Day = new javax.swing.JTextField();
        lbErrorCheckOutDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfCheckOutDate_Month = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfCheckOutDate_Year = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRoomInformation = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnRoomDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 250, 236));

        jPanel2.setBackground(new java.awt.Color(255, 250, 236));

        cbGuests.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cbGuests.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Huésped", "2 Huéspedes", "3 Huéspedes. 4 Huéspedes. 5 Huéspedes" }));

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel1.setText("Huéspedes");

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 61, 61));
        jLabel4.setText("Fecha de entrada");

        tfCheckInDate_Day.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckInDate_Day.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckInDate_Day.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckInDate_Day.setText("00");
        tfCheckInDate_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckInDate_DayActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(61, 61, 61));
        jLabel6.setText("/");

        tfCheckInDate_Month.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckInDate_Month.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckInDate_Month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckInDate_Month.setText("00");
        tfCheckInDate_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckInDate_MonthActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(61, 61, 61));
        jLabel7.setText("/");

        tfCheckInDate_Year.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckInDate_Year.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckInDate_Year.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckInDate_Year.setText("0000");
        tfCheckInDate_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckInDate_YearActionPerformed(evt);
            }
        });

        lbErrorCheckInDate.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lbErrorCheckInDate.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lbErrorCheckInDate.setText("Error, escriba una fecha válida.");

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(61, 61, 61));
        jLabel5.setText("Fecha de salida");

        tfCheckOutDate_Day.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckOutDate_Day.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckOutDate_Day.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckOutDate_Day.setText("00");
        tfCheckOutDate_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckOutDate_DayActionPerformed(evt);
            }
        });

        lbErrorCheckOutDate.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lbErrorCheckOutDate.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lbErrorCheckOutDate.setText("Error, escriba una fecha válida.");

        jLabel8.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(61, 61, 61));
        jLabel8.setText("/");

        tfCheckOutDate_Month.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckOutDate_Month.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckOutDate_Month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckOutDate_Month.setText("00");
        tfCheckOutDate_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckOutDate_MonthActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(61, 61, 61));
        jLabel9.setText("/");

        tfCheckOutDate_Year.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tfCheckOutDate_Year.setForeground(new java.awt.Color(204, 204, 204));
        tfCheckOutDate_Year.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCheckOutDate_Year.setText("0000");
        tfCheckOutDate_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckOutDate_YearActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(245, 236, 213));
        btnLogin.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(61, 61, 61));
        btnLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ismael Lima\\Documents\\GitHub\\SEGUNDO SEMESTRE - POO\\POOP2ProyectoLimaLanche\\P2Proyecto_Lanche_Lima\\src\\main\\java\\icons\\login.png")); // NOI18N
        btnLogin.setText("Iniciar sesión");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfCheckInDate_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel6)
                                        .addGap(3, 3, 3)
                                        .addComponent(tfCheckInDate_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel7)
                                        .addGap(3, 3, 3)
                                        .addComponent(tfCheckInDate_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfCheckOutDate_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel8)
                                        .addGap(3, 3, 3)
                                        .addComponent(tfCheckOutDate_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel9)
                                        .addGap(3, 3, 3)
                                        .addComponent(tfCheckOutDate_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbErrorCheckInDate)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbErrorCheckOutDate))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCheckInDate_Day)
                    .addComponent(jLabel6)
                    .addComponent(tfCheckInDate_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfCheckInDate_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbErrorCheckInDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCheckOutDate_Day)
                    .addComponent(jLabel8)
                    .addComponent(tfCheckOutDate_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfCheckOutDate_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbErrorCheckOutDate)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(6, 6, 6))
        );

        jPanel6.setBackground(new java.awt.Color(245, 236, 213));

        tbRoomInformation.setBackground(new java.awt.Color(245, 236, 213));
        tbRoomInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número de habitación", "Tipo de habitación", "Precio por noche"
            }
        ));
        jScrollPane1.setViewportView(tbRoomInformation);

        btnSearch.setBackground(new java.awt.Color(87, 142, 126));
        btnSearch.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 250, 236));
        btnSearch.setText("Buscar");

        btnRoomDetails.setBackground(new java.awt.Color(87, 142, 126));
        btnRoomDetails.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnRoomDetails.setForeground(new java.awt.Color(255, 250, 236));
        btnRoomDetails.setText("Detalles de la habitación");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRoomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(btnRoomDetails)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 61, 61));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Urban Luxe - Santo Domingo de los Tsáchilas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCheckInDate_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckInDate_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckInDate_DayActionPerformed

    private void tfCheckInDate_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckInDate_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckInDate_MonthActionPerformed

    private void tfCheckInDate_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckInDate_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckInDate_YearActionPerformed

    private void tfCheckOutDate_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckOutDate_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckOutDate_DayActionPerformed

    private void tfCheckOutDate_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckOutDate_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckOutDate_MonthActionPerformed

    private void tfCheckOutDate_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckOutDate_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckOutDate_YearActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsRoomsInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsRoomsInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsRoomsInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsRoomsInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsRoomsInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnRoomDetails;
    public javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbGuests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbErrorCheckInDate;
    public javax.swing.JLabel lbErrorCheckOutDate;
    private javax.swing.JTable tbRoomInformation;
    public javax.swing.JTextField tfCheckInDate_Day;
    public javax.swing.JTextField tfCheckInDate_Month;
    public javax.swing.JTextField tfCheckInDate_Year;
    public javax.swing.JTextField tfCheckOutDate_Day;
    public javax.swing.JTextField tfCheckOutDate_Month;
    public javax.swing.JTextField tfCheckOutDate_Year;
    // End of variables declaration//GEN-END:variables
}
